FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
#EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /BANK
COPY ["bankTest.csproj", "./"]
RUN dotnet restore "bankTest.csproj"
COPY . .
WORKDIR "/BANK/."
RUN dotnet build "bankTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish  "bankTest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
#When you opt-out this allows the container to run as readonly
ENV COMPlus__EnableDiagnostics=0 
ENTRYPOINT ["dotnet", "bankTest.dll"]